AllCops:
  TargetRubyVersion: 2.6

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 28

Metrics/BlockLength:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 11

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 11
